<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPmx9owf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPmx9owf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPmx9owf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPmx9owf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPmx9owf\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pmx9owf',
    'container.build_id' => '00aa679c',
    'container.build_time' => 1682410760,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPmx9owf');
