<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZHKaEpt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZHKaEpt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZHKaEpt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZHKaEpt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZHKaEpt\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZHKaEpt',
    'container.build_id' => 'e5d03c4d',
    'container.build_time' => 1682409124,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZHKaEpt');
